### PR TITLE
Legion fixes + blizzard style power bars

### PR DESCRIPTION
**Pull request by bbeny123**
- PVP Icon - more blizzlike size and position
- More blizzlike totem bars
- More detailed % ("both" option)
- Added supoport for blizzard's like maelstorm, insanity and luna power bars (to working required my fork of oUF - with official oUF this feature just won't work)

### CODE REVIEW

**Comment by bbeny123** [comment]
Blizz style of legion's power bar:
changes

**Comment by Sticklord** [comment]
Ah thanks. Seems like you got the totems better working than me. But you're removing so much stuff, like the painting of the elements, return of the class alt power bars and deleting commented out code, which i might use later. Please remove that and I'll merge it.

**Comment by bbeny123** [comment]
Now should be OK :)

**Comment by Sticklord** [comment]
Very nice, merging it.

**Pull request merged**
